### ISSUE TITLE
Website for club

### ISSUE THREAD

**Issue by wbnns** [nopara73/WasabiResearchExperience#1]
Inspiration / idea for layout: https://www.sfbitcoindevs.org/
Code repository: https://github.com/leishman/sf-bitcoin-devs

**Comment by nopara73** [comment]
Nice! If this becomes a thing, then we'll definitely consider it.

**Comment by AvivMilner** [comment]
I like this idea as well, once we get to three paper reviews we should do it.

**Comment by wbnns** [comment]
Almost time? Let me know if you'd like me to put a draft together.

**Comment by nopara73** [comment]
I was thinking more like half a year or something:)

**Comment by wbnns** [comment]
Ah, ok, no worries - I was going off Aviv's comment. Just let me know when you're ready, then (if you still want help at that time, that is).

**Comment by nopara73** [comment]
Thank you!

**Comment by wbnns** [comment]
It didn't take much effort, and was thinking that it might be a lot of work to catch up half a year. So I went ahead and put something together anyway: https://wasabiresearch.org

Happy to transfer over the domain if you all want it; I've opened #6 with all of the code. If still unwanted, feel free to disregard, and no worries.

Cheers.

**Comment by AvivMilner** [comment]
What an excellent page - I like it!

**Comment by wbnns** [comment]
@AvivMilner Thank you.
