### ISSUE TITLE
Consider adding slides as PDFs instead of PPTs 

### ISSUE THREAD

**Issue by wbnns** [nopara73/WasabiResearchExperience#18]
For people who don't have Powerpoint, perhaps it is worth considering exporting the slides to PDF and making them available in that format (as opposed to raw PPT files). Might enable a wider audience to follow along and/or share material.

Cc: @AvivMilner @nopara73

**Comment by AvivMilner** [comment]
I'm working on it, hopefully will be done today

**Comment by AvivMilner** [comment]
Ok, I did it! From now on all powerpoints will be uploaded in both formats. Thank you @wbnns for the great suggestion (also you can go through the slides without download on the website now!)

**Comment by AvivMilner** [comment]
Aviv. Out.

**Comment by wbnns** [comment]
@AvivMilner Ok, awesome. :)
