### ISSUE TITLE
Generate Shared Secret Key from addresses

### ISSUE THREAD

**Issue by lontivero** [nopara73/WasabiResearchExperience#19]
Just for the record, in the last session about CoinShuffle++ @nopara73 mentioned that with taproot outputs, given they contains the public key, they can be used to calculate a shared secret which would allow us to encrypt messages to the owners of those utxos (containing for example our onion endpoint) and then implement a P2E scheme.

I suggested that that could be already done with any address (even p2pkh) but **that is incorrect** because the DH key exchange works as follow: 

```
A = aG   # where 'A' is the Alice public key, 'a' is the Alice private key and 'G' is the curve generator.
B = bG   # the same for Bob 
```

Alice sends her public key 'A' to Bob. Then Bob calculates the shared secret key as follows:
```
SSK = bA  # what is the same to say b(aG) or baG
```
Next, Bob sends his public key 'B' to Alice and she calculates the shared secret key as follows: 
```
SSK = aB # what is the same to say a(bG) or abG
```
As we know `ab` is the same that `ba` so, both Alice and Bob get the exactly same secret shared key.

However, if instead of having the Alice public key she shares the hash of her public key `H(A)` then there is no way to compute a shared secret key.

**Comment by AvivMilner** [comment]
Yes, that is why in SNICKER Gibson recommended to use addresses that had previously spent outputs. In the spending of outputs, the  public key is revealed.

**Comment by nopara73** [comment]
ACK
