### ISSUE TITLE
Broken links / Youtube

### ISSUE THREAD

**Issue by wbnns** [nopara73/WasabiResearchExperience#8]
Since the files/folders were recently moved, the links in the [YouTube videos](https://www.youtube.com/playlist?list=PLPwc75tPMdsgTYlu9dJZlosCm0s7WmIpF) need to be updated (i.e. the slides).

With #6, I left the folder/file architecture as-is, and just added the website alongside it to ensure the links would be preserved (there are most likely other links on reddit and/or other social media that may be pointing to the slides).

8c2fac3 and ad014be yesterday changed the overall architecture and broke the links. Thinking we should either:

1. Move the files back
2. Store the powerpoints in `assets/` going forward, link to them there, and update the relevant links on the YouTube channel (recommended - #7)

For 2, the effect of other links potentially still being broken in cyberspace may be negligible, since the meetings have passed. But Youtube would be important to update since the individual videos are still accumulating views and are linked to as a place to go to reference past meetings.

Cc: @AvivMilner @nopara73

**Comment by nopara73** [comment]
Fixed under YouTube. Thank you!
